//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int id_document { get; set; }
        public int id_check { get; set; }
        public int id_organization { get; set; }
    
        public virtual Check Check { get; set; }
    }
}
