//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narushenia
    {
        public int id_narushen { get; set; }
        public int id_question { get; set; }
        public string comment { get; set; }
        public string photo { get; set; }
        public string correction { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
