//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int id_organization { get; set; }
        public string name { get; set; }
        public int id_person { get; set; }
        public int id_adress { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Person Person { get; set; }
    }
}
